import { Platform } from 'react-native';
import { post } from '../services/api';

export interface S3UploadResult {
  url: string;
  publicId: string;
}

/**
 * Uploads a file directly to AWS S3 using a Pre-signed URL generated by the backend.
 * 
 * @param localUri The local URI of the file (e.g. from image picker or document picker)
 * @param fileType The MIME type of the file (e.g. 'image/jpeg', 'application/pdf')
 * @param folder The folder path/prefix inside the S3 bucket (e.g. 'profiles', 'documents')
 * @param onProgress Optional callback to track upload progress (0 to 100)
 */
export const uploadToS3 = async (
  localUri: string,
  fileType: string,
  folder: string = 'general',
  onProgress?: (progress: number) => void
): Promise<S3UploadResult> => {
  try {
    // 1. Prepare file name
    const filename = localUri.split('/').pop() || `file_${Date.now()}`;

    // 2. Request pre-signed URL from backend
    const response = await post<{
      success: boolean;
      uploadUrl: string;
      publicUrl: string;
      key: string;
    }>('/upload/presigned-url', {
      fileName: filename,
      fileType: fileType,
      folder: folder,
    });

    if (!response || !response.uploadUrl || !response.publicUrl) {
      throw new Error('Failed to generate pre-signed S3 URL from backend');
    }

    const { uploadUrl, publicUrl, key } = response;

    // 3. Format URI correctly for Android/iOS native networking
    let formattedUri = localUri;
    if (Platform.OS === 'android' && !localUri.startsWith('file://') && !localUri.startsWith('content://') && localUri.startsWith('/')) {
      formattedUri = `file://${localUri}`;
    }

    const fileBody = {
      uri: formattedUri,
      type: fileType,
      name: filename,
    };

    // 4. Upload file using XMLHttpRequest (fully compatible with RN filesystem streaming)
    await new Promise<void>((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('PUT', uploadUrl);
      xhr.setRequestHeader('Content-Type', fileType);

      if (onProgress) {
        xhr.upload.addEventListener('progress', (event) => {
          if (event.lengthComputable) {
            const progress = Math.round((event.loaded / event.total) * 100);
            onProgress(progress);
          }
        });
      }

      xhr.addEventListener('load', () => {
        if (xhr.status === 200 || xhr.status === 201) {
          resolve();
        } else {
          reject(new Error(`S3 upload failed with status code ${xhr.status}`));
        }
      });

      xhr.addEventListener('error', () => {
        reject(new Error('Network error during S3 upload'));
      });

      xhr.addEventListener('abort', () => {
        reject(new Error('S3 upload was aborted'));
      });

      xhr.send(fileBody as any);
    });

    return {
      url: publicUrl,
      publicId: key,
    };
  } catch (error) {
    console.error('Error in uploadToS3:', error);
    throw error;
  }
};
